arch:
 - amd64
 - ppc64le
language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "6"
  - "8"
  - "10"
jobs:
 exclude:
  - arch: ppc64le
    nodejs:
     - "0.10"
  - arch: ppc64le
    nodejs:
     - "0.12"
